name: Publish

on:
  release:
    types: [published]

jobs:
  push_to_registry:
    name: Push image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@d398f07826957cd0a18ea1b059cf1207835e60bc
        with:
          username: jetprotocol
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@ee266832e57cb510bc6060ce5129df0529f119df
        with:
          images: jetprotocol/builder
      
      - name: Build and push Docker image
        uses: docker/build-push-action@965c6a410d446a30e95d35052c67d6eded60dad6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}